# Generated by Django 5.0 on 2023-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPKpH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('k', models.IntegerField(default=0)),
                ('ph', models.IntegerField(default=0)),
            ],
        ),
    ]
