# Generated by Django 5.0 on 2023-12-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkmeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npkph',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npkph',
            name='t',
            field=models.IntegerField(default=0),
        ),
    ]
